# Generated by Django 3.0.3 on 2020-02-10 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Viewable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title: (Will not be visible on production)')),
                ('file_type', models.CharField(choices=[('img', 'Image'), ('vdo', 'Video'), ('pge', 'HTML Page')], default='img', max_length=3)),
                ('file', models.FileField(upload_to='viewables')),
            ],
        ),
    ]
