# Generated by Django 3.0.3 on 2020-02-11 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name of the screen: (Will not be visible on production)')),
                ('screen_pin', models.IntegerField(default=6837)),
                ('current_view_id', models.IntegerField(default=0)),
            ],
        ),
    ]
