# Generated by Django 3.0.3 on 2020-02-11 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runner', '0004_auto_20200211_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='screen',
            name='background_color',
            field=models.CharField(choices=[('#14B4A0', 'Praedinius Green'), ('#2382BE', 'Praedinius Blue')], default='#2382BE', max_length=7),
        ),
        migrations.AlterField(
            model_name='screen',
            name='screen_pin',
            field=models.IntegerField(default=2257),
        ),
    ]
