# Generated by Django 2.2.7 on 2021-09-09 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runner', '0011_auto_20200211_2119'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='screen',
            options={'verbose_name': 'Scherm', 'verbose_name_plural': 'Schermen'},
        ),
        migrations.AlterModelOptions(
            name='viewable',
            options={'verbose_name': 'dia', 'verbose_name_plural': "dia's"},
        ),
        migrations.AddField(
            model_name='viewable',
            name='screens',
            field=models.ManyToManyField(blank=True, null=True, to='runner.Screen'),
        ),
        migrations.AlterField(
            model_name='screen',
            name='background_color',
            field=models.CharField(choices=[('#14B4A0', 'Praedinius Green'), ('#2382BE', 'Praedinius Blue'), ('#EEEEEE', 'Normal White'), ('#111111', 'Abnoxious Black'), ('#d12f24', 'Kinda Red'), ('#ffd752', 'Warning Yellow'), ('#902bd9', 'Maybe Purple'), ('#f24ea8', 'Absolute Pink')], default='#2382BE', max_length=7),
        ),
        migrations.AlterField(
            model_name='screen',
            name='content_border_color',
            field=models.CharField(choices=[('#14B4A0', 'Praedinius Green'), ('#2382BE', 'Praedinius Blue'), ('#EEEEEE', 'Normal White'), ('#111111', 'Abnoxious Black'), ('#d12f24', 'Kinda Red'), ('#ffd752', 'Warning Yellow'), ('#902bd9', 'Maybe Purple'), ('#f24ea8', 'Absolute Pink')], default='#ffffff', max_length=7),
        ),
        migrations.AlterField(
            model_name='screen',
            name='screen_pin',
            field=models.IntegerField(default=6475),
        ),
    ]
