# Generated by Django 2.2.7 on 2021-09-11 20:13

from django.db import migrations, models
import runner.models


class Migration(migrations.Migration):

    dependencies = [
        ('runner', '0012_auto_20210909_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screen',
            name='screen_pin',
            field=models.IntegerField(default=6772),
        ),
        migrations.AlterField(
            model_name='viewable',
            name='file',
            field=models.FileField(upload_to=runner.models.PathAndRename('viewables')),
        ),
        migrations.CreateModel(
            name='Automation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title: (Short description)')),
                ('datetime', models.DateTimeField(verbose_name='Execute on:')),
                ('to_disable', models.ManyToManyField(blank=True, null=True, related_name='to_disable', to='runner.Viewable', verbose_name='Slides to disable:')),
                ('to_enable', models.ManyToManyField(blank=True, null=True, related_name='to_enable', to='runner.Viewable', verbose_name='Slides to enable:')),
            ],
        ),
    ]
